imports:
    - { resource: services/repositories.yml }

services:
    acme_news.service.news:
        class: Acme\AcmeNewsBundle\Services\NewsService
        arguments:
          - "@acme_news.repository.news"
          - "@knp_paginator"
